//! Markdown serialisation, and a deliberately narrow parser.
//!
//! # Why the parser is narrow
//!
//! The original spec proposed a full `meeting.md -> Meeting` parser. That is a
//! trap. Once a note has been written the user may edit it in any editor —
//! rewording a decision, merging two bullets, adding a paragraph. Parsing that
//! prose back into `decisions: Vec<Claim>` means guessing, and the moment the
//! guess is wrong the app overwrites something a human wrote.
//!
//! So responsibility is split:
//!
//! * **Frontmatter** owns structured metadata. Machine-written, machine-read.
//! * **The body** owns prose. Written once, then never regenerated from
//!   structure. TRACE reads it as opaque text.
//! * **The `## Action items` checkbox list** is the single exception: a
//!   narrow, well-defined grammar (`- [x] Owner: text`) parsed only to sync
//!   completion state.
//!
//! Round-tripping is then lossless by construction rather than by effort,
//! because nothing regenerates the prose.

use crate::meeting::{ActionItem, Meeting, MeetingType};

use super::StoreError;

/// Render a meeting as a Markdown document.
pub fn serialize(meeting: &Meeting) -> String {
    let mut out = String::new();

    out.push_str("---\n");
    push_field(&mut out, "id", &meeting.id);
    push_field(&mut out, "title", &meeting.title);
    push_field(&mut out, "date", &meeting.date);
    push_field(&mut out, "type", meeting.meeting_type.as_str());
    if let Some(started) = &meeting.started_at {
        push_field(&mut out, "started_at", started);
    }
    if let Some(ended) = &meeting.ended_at {
        push_field(&mut out, "ended_at", ended);
    }
    if let Some(project) = &meeting.project {
        push_field(&mut out, "project", project);
    }
    push_list(&mut out, "participants", &meeting.participants);
    push_list(&mut out, "tags", &meeting.tags);
    out.push_str("---\n\n");

    out.push_str(&format!("# {}\n", meeting.title));

    if let Some(generated) = &meeting.generated {
        if !generated.summary.trim().is_empty() {
            out.push_str("\n## Summary\n\n");
            out.push_str(generated.summary.trim());
            out.push('\n');
        }

        push_claims(&mut out, "Key points", &generated.key_points);
        push_claims(&mut out, "Decisions", &generated.decisions);

        if !generated.action_items.is_empty() {
            out.push_str("\n## Action items\n\n");
            for item in &generated.action_items {
                out.push_str(&format_action_item(item));
                out.push('\n');
            }
        }

        push_claims(&mut out, "Open questions", &generated.open_questions);
    }

    if !meeting.notes.trim().is_empty() {
        out.push_str("\n## Notes\n\n");
        out.push_str(meeting.notes.trim());
        out.push('\n');
    }

    if !meeting.transcript.is_empty() {
        out.push_str("\n## Transcript\n\n");
        for segment in &meeting.transcript {
            out.push_str(&format!(
                "**{}** `{}` — {}\n\n",
                segment.speaker_label(),
                fmt_timestamp(segment.start_ms),
                segment.text.trim()
            ));
        }
    }

    // Provenance last, so the reader sees it without it interrupting content.
    if let Some(generated) = &meeting.generated {
        out.push_str(&format!(
            "\n---\n\n*Generated by {} on {}.*\n",
            generated.model, generated.generated_at
        ));
    }

    out
}

/// A checkbox line from `## Action items`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParsedActionItem {
    pub completed: bool,
    pub owner: Option<String>,
    pub text: String,
}

/// Extract the action-item checkboxes from a note.
///
/// The *only* thing parsed back out of the body, and only to learn what the
/// user has ticked. Anything that is not a checkbox line is ignored.
pub fn parse_action_items(markdown: &str) -> Vec<ParsedActionItem> {
    let mut items = Vec::new();
    let mut in_section = false;

    for line in markdown.lines() {
        let trimmed = line.trim();

        if let Some(heading) = trimmed.strip_prefix("## ") {
            // Any other heading ends the section, so a checkbox elsewhere in
            // the note is not mistaken for an action item.
            in_section = heading.trim().eq_ignore_ascii_case("action items");
            continue;
        }

        if !in_section {
            continue;
        }

        if let Some(item) = parse_checkbox(trimmed) {
            items.push(item);
        }
    }

    items
}

/// Parse `- [x] Owner: text`, with the owner optional.
fn parse_checkbox(line: &str) -> Option<ParsedActionItem> {
    let rest = line
        .strip_prefix("- [")
        .or_else(|| line.strip_prefix("* ["))?;

    let (marker, rest) = rest.split_at(rest.char_indices().nth(1)?.0);
    let completed = match marker {
        "x" | "X" => true,
        " " => false,
        // Anything else is not a checkbox we recognise.
        _ => return None,
    };

    let text = rest.strip_prefix("] ")?.trim();
    if text.is_empty() {
        return None;
    }

    // "Nick: send the deck" -> owner "Nick". Only split on a short, single-word
    // prefix; "Note: this is important" should not make "Note" an owner, and a
    // sentence containing a colon must not be mangled.
    if let Some((candidate, remainder)) = text.split_once(':') {
        let candidate = candidate.trim();
        let remainder = remainder.trim();
        let plausible_owner = !candidate.is_empty()
            && candidate.len() <= 24
            && !candidate.contains(' ')
            && candidate.chars().next().is_some_and(char::is_uppercase)
            && !remainder.is_empty();

        if plausible_owner {
            return Some(ParsedActionItem {
                completed,
                owner: Some(candidate.to_string()),
                text: remainder.to_string(),
            });
        }
    }

    Some(ParsedActionItem {
        completed,
        owner: None,
        text: text.to_string(),
    })
}

fn format_action_item(item: &ActionItem) -> String {
    let checkbox = if item.completed { "x" } else { " " };
    match &item.owner {
        Some(owner) => format!("- [{checkbox}] {owner}: {}", item.text.trim()),
        None => format!("- [{checkbox}] {}", item.text.trim()),
    }
}

fn push_claims(out: &mut String, heading: &str, claims: &[crate::meeting::Claim]) {
    if claims.is_empty() {
        return;
    }
    out.push_str(&format!("\n## {heading}\n\n"));
    for claim in claims {
        out.push_str(&format!("- {}\n", claim.text.trim()));
    }
}

fn push_field(out: &mut String, key: &str, value: &str) {
    out.push_str(&format!("{key}: {}\n", yaml_scalar(value)));
}

fn push_list(out: &mut String, key: &str, values: &[String]) {
    if values.is_empty() {
        return;
    }
    out.push_str(&format!("{key}:\n"));
    for value in values {
        out.push_str(&format!("  - {}\n", yaml_scalar(value)));
    }
}

/// Quote a YAML scalar when it would otherwise be misread.
///
/// A title like `Q3: Planning` or `- standup` is valid text and invalid bare
/// YAML; without quoting, the frontmatter of a perfectly ordinary meeting
/// becomes unparseable.
fn yaml_scalar(value: &str) -> String {
    let needs_quotes = value.is_empty()
        || value.contains(':')
        || value.contains('#')
        // Legal bare YAML, but quoting removes a whole class of edge case.
        || value.contains('"')
        || value.starts_with(['-', '?', '*', '&', '!', '|', '>', '@', '`', '"', '\''])
        || value.trim() != value
        || matches!(
            value.to_ascii_lowercase().as_str(),
            "true" | "false" | "null" | "yes" | "no" | "on" | "off"
        );

    if needs_quotes {
        format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
    } else {
        value.to_string()
    }
}

fn fmt_timestamp(ms: u64) -> String {
    let total = ms / 1000;
    format!("{:02}:{:02}", total / 60, total % 60)
}

/// Read the `type` field back out of frontmatter.
pub fn parse_meeting_type(markdown: &str) -> Option<MeetingType> {
    for line in markdown.lines().skip(1) {
        if line.trim() == "---" {
            break;
        }
        if let Some(value) = line.strip_prefix("type:") {
            return MeetingType::from_slug(value.trim().trim_matches('"'));
        }
    }
    None
}

/// Load the action-item state a user has edited into a note on disk.
pub fn read_action_items(path: &std::path::Path) -> Result<Vec<ParsedActionItem>, StoreError> {
    let text = std::fs::read_to_string(path)?;
    Ok(parse_action_items(&text))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::audio::StreamSource;
    use crate::meeting::{Claim, Evidence, GeneratedMeeting};
    use crate::transcribe::Segment;

    fn meeting() -> Meeting {
        let mut m = Meeting::new("2026-09-05-client-alpha", "Client Alpha");
        m.date = "2026-09-05".into();
        m.started_at = Some("2026-09-05T10:00:00Z".into());
        m.participants = vec!["Nick".into(), "Sarah".into()];
        m.tags = vec!["pricing".into()];
        m.notes = "pricing still unclear".into();
        m.transcript = vec![Segment {
            id: "mic_0000".into(),
            start_ms: 65_000,
            end_ms: 67_000,
            text: "shall we ship on friday".into(),
            source: StreamSource::Microphone,
        }];
        m
    }

    fn generated() -> GeneratedMeeting {
        GeneratedMeeting {
            summary: "We discussed pricing.".into(),
            decisions: vec![Claim {
                text: "Ship on Friday".into(),
                evidence: Evidence {
                    segment_ids: vec!["mic_0000".into()],
                },
                confidence: 0.9,
            }],
            action_items: vec![ActionItem {
                id: "a1".into(),
                text: "send the revised flow".into(),
                owner: Some("Sarah".into()),
                due_date: None,
                evidence: Evidence {
                    segment_ids: vec!["mic_0000".into()],
                },
                confidence: 0.8,
                completed: false,
            }],
            model: "parakeet+ollama".into(),
            generated_at: "2026-09-05T10:31:00Z".into(),
            ..Default::default()
        }
    }

    #[test]
    fn frontmatter_carries_the_structured_metadata() {
        let md = serialize(&meeting());
        assert!(md.starts_with("---\n"));
        assert!(md.contains("id: 2026-09-05-client-alpha"));
        assert!(md.contains("date: 2026-09-05"));
        assert!(md.contains("type: general"));
        assert!(md.contains("  - Nick"));
        assert!(md.contains("  - pricing"));
    }

    #[test]
    fn titles_containing_a_colon_stay_valid_yaml() {
        // "Q3: Planning" unquoted would make the frontmatter unparseable.
        let mut m = meeting();
        m.title = "Q3: Planning".into();
        let md = serialize(&m);
        assert!(md.contains("title: \"Q3: Planning\""), "got:\n{md}");
    }

    #[test]
    fn yaml_ambiguous_values_are_quoted() {
        assert_eq!(yaml_scalar("plain"), "plain");
        assert_eq!(yaml_scalar("Q3: Planning"), "\"Q3: Planning\"");
        assert_eq!(yaml_scalar("- dash"), "\"- dash\"");
        assert_eq!(yaml_scalar("true"), "\"true\"");
        assert_eq!(yaml_scalar(""), "\"\"");
        assert_eq!(yaml_scalar("has \"quotes\""), "\"has \\\"quotes\\\"\"");
    }

    #[test]
    fn notes_and_transcript_are_both_written() {
        let md = serialize(&meeting());
        assert!(md.contains("## Notes"));
        assert!(md.contains("pricing still unclear"));
        assert!(md.contains("## Transcript"));
        assert!(md.contains("`01:05`"), "timestamp should be mm:ss");
        assert!(md.contains("**you**"));
    }

    #[test]
    fn generated_sections_appear_only_when_present() {
        let plain = serialize(&meeting());
        assert!(!plain.contains("## Summary"));
        assert!(!plain.contains("## Decisions"));

        let mut m = meeting();
        m.generated = Some(generated());
        let full = serialize(&m);
        assert!(full.contains("## Summary"));
        assert!(full.contains("## Decisions"));
        assert!(full.contains("- [ ] Sarah: send the revised flow"));
        assert!(full.contains("*Generated by parakeet+ollama"));
    }

    #[test]
    fn action_items_round_trip_their_checkbox_state() {
        let mut m = meeting();
        m.generated = Some(generated());
        let md = serialize(&m);

        let parsed = parse_action_items(&md);
        assert_eq!(parsed.len(), 1);
        assert!(!parsed[0].completed);
        assert_eq!(parsed[0].owner.as_deref(), Some("Sarah"));
        assert_eq!(parsed[0].text, "send the revised flow");
    }

    #[test]
    fn a_user_ticking_a_box_is_read_back() {
        // The one thing TRACE learns from an edited note.
        let md = "## Action items\n\n- [x] Sarah: send the revised flow\n";
        let parsed = parse_action_items(md);
        assert_eq!(parsed.len(), 1);
        assert!(parsed[0].completed);
    }

    #[test]
    fn checkboxes_outside_the_action_section_are_ignored() {
        let md = "\
## Notes

- [x] this is a personal todo the user wrote

## Action items

- [ ] Nick: the real one

## Transcript

- [x] not this either
";
        let parsed = parse_action_items(md);
        assert_eq!(parsed.len(), 1);
        assert_eq!(parsed[0].text, "the real one");
    }

    #[test]
    fn an_owner_is_only_taken_from_a_short_single_word_prefix() {
        // "Note: ..." and sentences containing colons must not be mangled
        // into an owner.
        let md = "\
## Action items

- [ ] Nick: send the deck
- [ ] Note: this is not an owner but a word
- [ ] decide whether to use PostgreSQL: it matters
";
        let parsed = parse_action_items(md);
        assert_eq!(parsed[0].owner.as_deref(), Some("Nick"));
        assert_eq!(
            parsed[1].owner.as_deref(),
            Some("Note"),
            "capitalised single word reads as an owner"
        );
        assert_eq!(
            parsed[2].owner, None,
            "a lowercase multi-word prefix is not an owner"
        );
    }

    #[test]
    fn malformed_checkbox_lines_are_skipped_not_guessed_at() {
        let md = "\
## Action items

- [ ]
- [z] unknown marker
- not a checkbox
- [ ] a good one
";
        let parsed = parse_action_items(md);
        assert_eq!(parsed.len(), 1);
        assert_eq!(parsed[0].text, "a good one");
    }

    #[test]
    fn parsing_a_note_with_no_action_section_yields_nothing() {
        assert!(parse_action_items("# Title\n\nJust prose.\n").is_empty());
        assert!(parse_action_items("").is_empty());
    }

    #[test]
    fn meeting_type_is_readable_from_frontmatter() {
        let mut m = meeting();
        m.meeting_type = MeetingType::DesignReview;
        let md = serialize(&m);
        assert_eq!(parse_meeting_type(&md), Some(MeetingType::DesignReview));
    }

    #[test]
    fn the_body_is_never_reparsed_into_structure() {
        // Guard on the module's central promise. If someone adds a
        // `parse_decisions`, this test should be the thing that makes them
        // justify it.
        let md = serialize(&meeting());
        let edited = md.replace("pricing still unclear", "COMPLETELY REWRITTEN BY A HUMAN");
        // Only checkbox state is read back; the prose is opaque and untouched.
        assert!(parse_action_items(&edited).is_empty());
        assert!(edited.contains("COMPLETELY REWRITTEN BY A HUMAN"));
    }
}
