/**
 * Sample notes for the gallery.
 *
 * Written as realistic meeting output rather than lorem ipsum, because the
 * whole point of looking at these is judging how real text reads: whether a
 * transcript stays legible at length, whether the generated half is
 * distinguishable at a glance, whether uppercase system labels are charming
 * or tiring. Placeholder text answers none of that.
 */

export const NOTE_ENHANCED = `---
id: 20260902-1400-pricing
title: Pricing page rework
date: 2026-09-02T14:00:00Z
type: general
participants: [you, Sarah, Dev]
---

# Pricing page rework

## Summary

The team reviewed the current pricing page and agreed it is doing too much at
once. Sarah walked through the drop-off data, which shows most visitors leave
at the comparison table rather than at the price itself. Dev raised that the
annual toggle is the single most expensive component on the page and is used
by a small fraction of visitors.

## Key points

- Drop-off concentrates at the comparison table, not the prices
- The annual/monthly toggle costs more to maintain than it earns
- Nobody could explain what the middle tier is for

## Decisions

- Remove the comparison table from the default view and put it behind a link
- Keep the annual toggle for now, revisit after the next billing cycle

## Action items

- [ ] Sarah: pull the last 90 days of drop-off by section
- [x] Dev: measure render cost of the toggle
- [ ] You: write the middle-tier positioning, or propose removing it

## Open questions

- What is the middle tier actually for?
- Does removing the table hurt enterprise enquiries?

## Notes

comparison table is the problem, not the price
middle tier — nobody could explain it
sarah has the drop-off numbers

## Transcript

**you** \`00:04\` — right, so the pricing page. I think we all know it is not working
**them** \`00:11\` — I pulled the numbers this morning. Most people leave at the comparison table
**you** \`00:19\` — not at the price itself?
**them** \`00:21\` — no, they get past the price fine. It is the table
**them** \`00:28\` — the other thing is the annual toggle. It is the most expensive component on that page by a long way
**you** \`00:36\` — used by how many?
**them** \`00:38\` — small fraction. I can get you the exact number
**you** \`00:44\` — let us keep it for now and look again after the next billing cycle
**them** \`00:51\` — fine by me
**you** \`00:55\` — the thing I keep coming back to is the middle tier. What is it for?
**them** \`01:02\` — honestly I do not know
**them** \`01:05\` — it has been there since before I joined

*Generated by ollama/qwen3:8b on 2026-09-02T15:12:00Z.*
`;

export const NOTE_RAW = `---
id: 20260901-1030-standup
title: Monday standup
date: 2026-09-01T10:30:00Z
type: general
participants: [you]
---

# Monday standup

## Notes

deploy went out friday, no incidents
blocked on the auth migration — waiting on ops
ask about the offsite dates

## Transcript

**you** \`00:02\` — deploy went out Friday evening, nothing broke
**them** \`00:09\` — good. Anything blocking you?
**you** \`00:12\` — the auth migration, I am waiting on ops for the staging credentials
`;

/** A meeting where the model correctly found nothing to extract. */
export const NOTE_NOTHING = `---
id: 20260903-0900-catchup
title: Catch-up with Dev
date: 2026-09-03T09:00:00Z
type: general
participants: [you, Dev]
---

# Catch-up with Dev

## Summary

A short catch-up. No decisions were made and no work was assigned.

## Decisions

## Action items

## Open questions

## Notes

good chat, nothing to action

## Transcript

**you** \`00:03\` — how was the weekend
**them** \`00:05\` — quiet, which was the point

*Generated by ollama/qwen3:8b on 2026-09-03T09:31:00Z.*
`;

/**
 * A long meeting. Generated rather than written out, because the question it
 * answers is about *length* — does a 90-minute transcript stay readable, does
 * the scroll position mean anything, does the collapsed section still work at
 * this size.
 */
export const NOTE_LONG = buildLongNote();

function buildLongNote(): string {
  const lines: string[] = [];
  const turns = [
    "so the first thing on the list is the migration timeline",
    "we said end of the month but that was before the auth work landed",
    "realistically that puts us into the second week",
    "does that affect the customer commitments",
    "no, those were always quarter-end",
    "then I think we are fine, it just looks worse on the board",
    "can we split it so the visible part ships on time",
    "possibly, the read path is separable from the write path",
    "let us cost that out before committing to it",
    "agreed, I will have numbers by Thursday",
    "next thing — the staging environment keeps falling over",
    "that is the memory limit, it has been the memory limit for a month",
    "why has nobody raised it",
    "it has been raised three times",
    "then let us just fix it, what does it cost",
    "about forty a month",
    "do it, that is not a conversation",
  ];

  for (let i = 0; i < 320; i++) {
    const mins = Math.floor((i * 17) / 60);
    const secs = (i * 17) % 60;
    const stamp = `${String(mins).padStart(2, "0")}:${String(secs).padStart(2, "0")}`;
    const who = i % 3 === 0 ? "you" : "them";
    lines.push(`**${who}** \`${stamp}\` — ${turns[i % turns.length]}`);
  }

  return `---
id: 20260828-0930-planning
title: Quarterly planning
date: 2026-08-28T09:30:00Z
type: general
participants: [you, Sarah, Dev, Priya]
---

# Quarterly planning

## Summary

A long session covering the migration timeline, the staging environment, and
budget for the next quarter. The migration slips by roughly one week because
of the auth work; the customer-facing commitments are unaffected because they
were always set to quarter-end.

## Decisions

- Fix the staging memory limit immediately
- Split the migration so the read path ships on the original date

## Action items

- [ ] Dev: cost out splitting the read and write paths, by Thursday
- [ ] Priya: raise the staging memory limit

## Notes

migration slips a week — auth work
staging memory limit, again
read/write split might save the date

## Transcript

${lines.join("\n\n")}

*Generated by ollama/qwen3:8b on 2026-08-28T11:20:00Z.*
`;
}
