/**
 * Splitting a saved note into what the user wrote and what the model added.
 *
 * These are genuinely different things and the product treats them that way:
 * the user's notes are typed by hand and never rewritten, the enhanced
 * sections are generated and can be regenerated or discarded. Being able to
 * see one without the other is what makes it obvious which is which.
 *
 * This reads only `## ` headings — the same narrow parsing the Markdown
 * module allows. It does not interpret prose.
 */

/** Headings written by synthesis, in the order they appear. */
const GENERATED = ["summary", "key points", "decisions", "action items", "open questions"];

export interface NoteSections {
  /** Frontmatter plus the title. */
  head: string;
  /** Generated sections, empty when the note has not been enhanced. */
  enhanced: string;
  /** The user's own typed notes. */
  notes: string;
  /** The transcript. */
  transcript: string;
  /** Provenance footer, if present. */
  footer: string;
  hasEnhanced: boolean;
  hasNotes: boolean;
}

export function splitSections(markdown: string): NoteSections {
  const lines = markdown.split("\n");

  const head: string[] = [];
  const enhanced: string[] = [];
  const notes: string[] = [];
  const transcript: string[] = [];
  const footer: string[] = [];

  // Everything before the first `##` belongs to the head, including
  // frontmatter and the title.
  let current: string[] = head;
  let seenSection = false;

  for (const line of lines) {
    if (line.startsWith("## ")) {
      seenSection = true;
      const heading = line.slice(3).trim().toLowerCase();
      if (heading === "notes") current = notes;
      else if (heading === "transcript") current = transcript;
      else if (GENERATED.includes(heading)) current = enhanced;
      // An unrecognised heading stays wherever we were, rather than being
      // dropped — a note the user hand-edited must not lose content here.
    } else if (seenSection && current === transcript && line.startsWith("*Generated by")) {
      current = footer;
    }
    current.push(line);
  }

  return {
    head: head.join("\n").trimEnd(),
    enhanced: enhanced.join("\n").trim(),
    notes: notes.join("\n").trim(),
    transcript: transcript.join("\n").trim(),
    footer: footer.join("\n").trim(),
    hasEnhanced: enhanced.length > 0,
    hasNotes: notes.some((l) => l.trim() && !l.startsWith("## ")),
  };
}

/**
 * The meeting's title, from the `# ` heading under the frontmatter, and
 * whatever else the head holds besides the frontmatter.
 *
 * Pulled out so the title can sit in the note's sticky header, where it
 * stays in view down a long note, instead of scrolling away with the body.
 */
export function splitTitle(head: string): { title: string | null; rest: string } {
  const lines = head.split("\n");
  let i = 0;
  // Skip frontmatter, which the body renderer would drop anyway.
  if (lines[0] === "---") {
    const close = lines.indexOf("---", 1);
    i = close === -1 ? 0 : close + 1;
  }
  const body = i;
  for (; i < lines.length; i++) {
    const line = lines[i] ?? "";
    if (line.startsWith("# ")) {
      // Frontmatter left out of `rest`: kept, it rendered as a stray rule.
      const rest = [...lines.slice(body, i), ...lines.slice(i + 1)].join("\n").trim();
      return { title: line.slice(2).trim(), rest };
    }
    if (line.trim() !== "") break;
  }
  return { title: null, rest: lines.slice(body).join("\n").trim() };
}

export interface Part {
  /** The `## ` heading's text, or null for anything before the first one. */
  heading: string | null;
  /** Everything under the heading, heading excluded. */
  body: string;
}

/**
 * Split a half of the note at its `## ` headings.
 *
 * Each becomes a section that can be framed — as a rule or a box, whichever
 * the theme draws — and collapsed on its own. Rendering the headings inline
 * between paragraphs, as before, meant no element wrapped a section, so the
 * boxed themes had nothing to draw a box around.
 */
export function splitParts(markdown: string): Part[] {
  const parts: Part[] = [];
  let current: Part = { heading: null, body: "" };
  const lines: string[] = [];

  const flush = () => {
    current.body = lines.join("\n").trim();
    if (current.heading !== null || current.body !== "") parts.push(current);
    lines.length = 0;
  };

  for (const line of markdown.split("\n")) {
    if (line.startsWith("## ")) {
      flush();
      current = { heading: line.slice(3).trim(), body: "" };
    } else {
      lines.push(line);
    }
  }
  flush();
  return parts;
}
