import { describe, expect, it } from "vitest";
import { splitSections } from "./sections";

const FULL = `---
id: sess-1
title: Client Alpha
---

# Client Alpha

## Summary

We discussed pricing.

## Decisions

- Ship on Friday

## Action items

- [ ] Sarah: send the deck

## Notes

pricing still unclear

## Transcript

**you** \`00:12\` — shall we ship on friday

*Generated by ollama/qwen3:8b on 2026-09-05T10:31:00Z.*
`;

const PLAIN = `---
id: sess-2
title: Raw
---

# Raw

## Notes

just my own words

## Transcript

**you** \`00:01\` — hello
`;

describe("splitSections", () => {
  it("separates generated sections from the user's own notes", () => {
    const s = splitSections(FULL);

    expect(s.enhanced).toContain("## Summary");
    expect(s.enhanced).toContain("## Decisions");
    expect(s.enhanced).toContain("Ship on Friday");

    expect(s.notes).toContain("pricing still unclear");
    // The user's notes must never appear inside the generated half.
    expect(s.enhanced).not.toContain("pricing still unclear");
  });

  it("keeps the transcript out of both", () => {
    const s = splitSections(FULL);
    expect(s.transcript).toContain("shall we ship on friday");
    expect(s.enhanced).not.toContain("shall we ship on friday");
    expect(s.notes).not.toContain("shall we ship on friday");
  });

  it("reports a note with no generated sections", () => {
    const s = splitSections(PLAIN);
    expect(s.hasEnhanced).toBe(false);
    expect(s.enhanced).toBe("");
    expect(s.hasNotes).toBe(true);
  });

  it("reports a note with no typed notes", () => {
    const s = splitSections(`---
id: x
---

# T

## Transcript

**you** \`00:01\` — hi
`);
    expect(s.hasNotes).toBe(false);
  });

  it("keeps frontmatter and title in the head", () => {
    const s = splitSections(FULL);
    expect(s.head).toContain("title: Client Alpha");
    expect(s.head).toContain("# Client Alpha");
  });

  it("separates the provenance footer from the transcript", () => {
    const s = splitSections(FULL);
    expect(s.footer).toContain("Generated by ollama/qwen3:8b");
    expect(s.transcript).not.toContain("Generated by");
  });

  it("does not lose content under an unrecognised heading", () => {
    // Someone may hand-edit a note and add their own section. Dropping it
    // would be destroying the user's work.
    const edited = `---
id: x
---

# T

## Notes

mine

## My own section

something I added by hand
`;
    const s = splitSections(edited);
    const everything = [s.head, s.enhanced, s.notes, s.transcript, s.footer].join("\n");
    expect(everything).toContain("something I added by hand");
  });

  it("handles an empty document without throwing", () => {
    const s = splitSections("");
    expect(s.hasEnhanced).toBe(false);
    expect(s.hasNotes).toBe(false);
  });
});
