/**
 * Splitting a saved note into what the user wrote and what the model added.
 *
 * These are genuinely different things and the product treats them that way:
 * the user's notes are typed by hand and never rewritten, the enhanced
 * sections are generated and can be regenerated or discarded. Being able to
 * see one without the other is what makes it obvious which is which.
 *
 * This reads only `## ` headings — the same narrow parsing the Markdown
 * module allows. It does not interpret prose.
 */

/** Headings written by synthesis, in the order they appear. */
const GENERATED = ["summary", "key points", "decisions", "action items", "open questions"];

export interface NoteSections {
  /** Frontmatter plus the title. */
  head: string;
  /** Generated sections, empty when the note has not been enhanced. */
  enhanced: string;
  /** The user's own typed notes. */
  notes: string;
  /** The transcript. */
  transcript: string;
  /** Provenance footer, if present. */
  footer: string;
  hasEnhanced: boolean;
  hasNotes: boolean;
}

export function splitSections(markdown: string): NoteSections {
  const lines = markdown.split("\n");

  const head: string[] = [];
  const enhanced: string[] = [];
  const notes: string[] = [];
  const transcript: string[] = [];
  const footer: string[] = [];

  // Everything before the first `##` belongs to the head, including
  // frontmatter and the title.
  let current: string[] = head;
  let seenSection = false;

  for (const line of lines) {
    if (line.startsWith("## ")) {
      seenSection = true;
      const heading = line.slice(3).trim().toLowerCase();
      if (heading === "notes") current = notes;
      else if (heading === "transcript") current = transcript;
      else if (GENERATED.includes(heading)) current = enhanced;
      // An unrecognised heading stays wherever we were, rather than being
      // dropped — a note the user hand-edited must not lose content here.
    } else if (seenSection && current === transcript && line.startsWith("*Generated by")) {
      current = footer;
    }
    current.push(line);
  }

  return {
    head: head.join("\n").trimEnd(),
    enhanced: enhanced.join("\n").trim(),
    notes: notes.join("\n").trim(),
    transcript: transcript.join("\n").trim(),
    footer: footer.join("\n").trim(),
    hasEnhanced: enhanced.length > 0,
    hasNotes: notes.some((l) => l.trim() && !l.startsWith("## ")),
  };
}
