import { describe, expect, it } from "vitest";
import { parseProvenance, splitParts, splitSections, splitTitle } from "./sections";

const FULL = `---
id: sess-1
title: Client Alpha
---

# Client Alpha

## Summary

We discussed pricing.

## Decisions

- Ship on Friday

## Action items

- [ ] Sarah: send the deck

## Notes

pricing still unclear

## Transcript

**you** \`00:12\` — shall we ship on friday

*Generated by ollama/qwen3:8b on 2026-09-05T10:31:00Z.*
`;

const PLAIN = `---
id: sess-2
title: Raw
---

# Raw

## Notes

just my own words

## Transcript

**you** \`00:01\` — hello
`;

describe("splitSections", () => {
  it("separates generated sections from the user's own notes", () => {
    const s = splitSections(FULL);

    expect(s.enhanced).toContain("## Summary");
    expect(s.enhanced).toContain("## Decisions");
    expect(s.enhanced).toContain("Ship on Friday");

    expect(s.notes).toContain("pricing still unclear");
    // The user's notes must never appear inside the generated half.
    expect(s.enhanced).not.toContain("pricing still unclear");
  });

  it("keeps the transcript out of both", () => {
    const s = splitSections(FULL);
    expect(s.transcript).toContain("shall we ship on friday");
    expect(s.enhanced).not.toContain("shall we ship on friday");
    expect(s.notes).not.toContain("shall we ship on friday");
  });

  it("reports a note with no generated sections", () => {
    const s = splitSections(PLAIN);
    expect(s.hasEnhanced).toBe(false);
    expect(s.enhanced).toBe("");
    expect(s.hasNotes).toBe(true);
  });

  it("reports a note with no typed notes", () => {
    const s = splitSections(`---
id: x
---

# T

## Transcript

**you** \`00:01\` — hi
`);
    expect(s.hasNotes).toBe(false);
  });

  it("keeps frontmatter and title in the head", () => {
    const s = splitSections(FULL);
    expect(s.head).toContain("title: Client Alpha");
    expect(s.head).toContain("# Client Alpha");
  });

  it("separates the provenance footer from the transcript", () => {
    const s = splitSections(FULL);
    expect(s.footer).toContain("Generated by ollama/qwen3:8b");
    expect(s.transcript).not.toContain("Generated by");
  });

  // The shape store/markdown.rs actually writes: a rule, a blank line, then
  // the provenance. The fixtures above leave the rule out, which is how a
  // stray <hr> at the foot of every real transcript went unseen.
  it("leaves the provenance's rule out of the transcript", () => {
    const real = FULL.replace("\n*Generated by", "\n---\n\n*Generated by");
    const s = splitSections(real);
    expect(s.transcript.trimEnd().endsWith("---")).toBe(false);
    expect(s.footer).toBe("*Generated by ollama/qwen3:8b on 2026-09-05T10:31:00Z.*");
  });

  it("keeps the provenance out of the user's notes when there is no transcript", () => {
    const noTranscript = `# T

## Summary

Short.

## Notes

my line

---

*Generated by ollama/qwen3:8b on 2026-09-05T10:31:00Z.*
`;
    const s = splitSections(noTranscript);
    expect(s.notes).toBe("## Notes\n\nmy line");
    expect(s.footer).toContain("Generated by");
  });

  it("does not lose content under an unrecognised heading", () => {
    // Someone may hand-edit a note and add their own section. Dropping it
    // would be destroying the user's work.
    const edited = `---
id: x
---

# T

## Notes

mine

## My own section

something I added by hand
`;
    const s = splitSections(edited);
    const everything = [s.head, s.enhanced, s.notes, s.transcript, s.footer].join("\n");
    expect(everything).toContain("something I added by hand");
  });

  it("handles an empty document without throwing", () => {
    const s = splitSections("");
    expect(s.hasEnhanced).toBe(false);
    expect(s.hasNotes).toBe(false);
  });
});

describe("splitTitle", () => {
  it("takes the title from under the frontmatter", () => {
    const { head } = splitSections(FULL);
    const { title, rest } = splitTitle(head);
    expect(title).toBe("Client Alpha");
    expect(rest).not.toContain("# Client Alpha");
    // Nor the frontmatter, which rendered as a stray rule.
    expect(rest).toBe("");
  });

  it("has no title when there is no heading", () => {
    expect(splitTitle("---\nid: x\n---\n\njust text").title).toBeNull();
  });
});

describe("splitParts", () => {
  it("gives each heading its own part, heading removed from the body", () => {
    const parts = splitParts("## Summary\n\nOne.\n\n## Key points\n\n- a\n- b");
    expect(parts).toEqual([
      { heading: "Summary", body: "One." },
      { heading: "Key points", body: "- a\n- b" },
    ]);
  });

  it("keeps text before the first heading rather than dropping it", () => {
    expect(splitParts("stray line\n\n## Notes\n\nmine")).toEqual([
      { heading: null, body: "stray line" },
      { heading: "Notes", body: "mine" },
    ]);
  });

  it("returns nothing for an empty half", () => {
    expect(splitParts("")).toEqual([]);
  });
});

describe("parseProvenance", () => {
  it("names the model without its provider, and reads the time", () => {
    const p = parseProvenance("*Generated by ollama/qwen3:8b on 2026-09-03T09:31:00Z.*");
    expect(p?.model).toBe("qwen3:8b");
    expect(p?.at?.toISOString()).toBe("2026-09-03T09:31:00.000Z");
  });

  it("returns null for anything it does not recognise, so the line is shown as written", () => {
    expect(parseProvenance("*Written by hand.*")).toBeNull();
  });

  it("keeps the model when the time cannot be read", () => {
    expect(parseProvenance("*Generated by qwen3:8b on yesterday.*")).toEqual({
      model: "qwen3:8b",
      at: null,
    });
  });
});
