/**
 * TRACE — terminal grammar components.
 *
 * The approved primitive set from docs/09-EASTER-EGGS.md, and deliberately
 * nothing more. New retro decoration should be argued for and added here,
 * not improvised at the call site.
 *
 * Utility classes below (`text-ink`, `font-mono`, `text-2xs`, `tracking-system`…)
 * are generated by Tailwind v4 from the `@theme` block in design/tokens.css.
 */

import type { ReactNode } from "react";

/* ------------------------------------------------------------------ *
 * SystemLabel — uppercase, tracked, monospace. The workhorse.
 *   NOTES     TRANSCRIPT     SIGNAL
 * ------------------------------------------------------------------ */

const LABEL_TONE = {
  faint: "text-ink-faint",
  muted: "text-ink-muted",
  phosphor: "text-phosphor",
} as const;

export function SystemLabel({
  children,
  tone = "faint",
}: {
  children: ReactNode;
  tone?: keyof typeof LABEL_TONE;
}) {
  return (
    <span className={`font-mono text-2xs uppercase tracking-system ${LABEL_TONE[tone]}`}>
      {children}
    </span>
  );
}

/* ------------------------------------------------------------------ *
 * Section — the canonical framing:
 *   ┌ 01  SUMMARY ──────────────────────────────────
 *
 * `index` is optional; omit it for unnumbered sections rather than
 * inventing a second framing style.
 * ------------------------------------------------------------------ */

export function Section({
  title,
  index,
  actions,
  children,
}: {
  title: string;
  index?: number;
  actions?: ReactNode;
  children: ReactNode;
}) {
  return (
    <section className="flex flex-col gap-3">
      <header className="flex items-center gap-2.5">
        <span aria-hidden className="font-mono text-2xs text-ink-faint/50">
          ┌
        </span>
        {index !== undefined && (
          <SystemLabel tone="phosphor">{String(index).padStart(2, "0")}</SystemLabel>
        )}
        <SystemLabel tone="muted">{title}</SystemLabel>
        <span aria-hidden className="trace-rule" />
        {actions}
      </header>
      {children}
    </section>
  );
}

/* ------------------------------------------------------------------ *
 * StatusDot — ● CAPTURING / ● TRANSCRIBING / ○ IDLE
 *
 * The single most important piece of state in the product. It pulses only
 * while genuinely capturing, so the motion always means the same thing.
 * ------------------------------------------------------------------ */

export type CaptureState = "idle" | "capturing" | "transcribing" | "processing" | "error";

const STATUS: Record<CaptureState, { label: string; dot: string; text: string; live: boolean }> = {
  idle: { label: "IDLE", dot: "bg-ink-faint", text: "text-ink-faint", live: false },
  capturing: { label: "CAPTURING", dot: "bg-phosphor", text: "text-phosphor", live: true },
  transcribing: { label: "TRANSCRIBING", dot: "bg-phosphor", text: "text-phosphor", live: true },
  processing: { label: "PROCESSING", dot: "bg-warn", text: "text-warn", live: true },
  error: { label: "SIGNAL LOST", dot: "bg-error", text: "text-error", live: false },
};

export function StatusDot({ state }: { state: CaptureState }) {
  const { label, dot, text, live } = STATUS[state];

  return (
    // role=status so a screen reader announces capture starting and stopping.
    <span role="status" className="inline-flex items-center gap-2">
      <span aria-hidden className={`size-1.5 rounded-full ${dot} ${live ? "trace-pulse" : ""}`} />
      <span className={`font-mono text-2xs uppercase tracking-system ${text}`}>{label}</span>
    </span>
  );
}

/* ------------------------------------------------------------------ *
 * Elapsed — 00:41:32
 * ------------------------------------------------------------------ */

export function formatElapsed(ms: number): string {
  const total = Math.max(0, Math.floor(ms / 1000));
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  const pad = (n: number) => String(n).padStart(2, "0");
  return h > 0 ? `${pad(h)}:${pad(m)}:${pad(s)}` : `${pad(m)}:${pad(s)}`;
}

export function Elapsed({ ms }: { ms: number }) {
  return (
    // tabular-nums stops the timer jittering as digits change width.
    <time
      className="font-mono text-base tabular-nums text-ink"
      dateTime={`PT${Math.round(ms / 1000)}S`}
    >
      {formatElapsed(ms)}
    </time>
  );
}

/* ------------------------------------------------------------------ *
 * Meter — MIC  ████████████░░░░  -12 dB
 *
 * Functional feedback, not decoration: it is how the user knows the
 * microphone is actually working before they trust a meeting to it.
 * ------------------------------------------------------------------ */

const METER_CELLS = 16;

export function Meter({
  label,
  /** Normalised 0..1 level. */
  level,
  db,
}: {
  label: string;
  level: number;
  db?: number | undefined;
}) {
  const clamped = Math.min(1, Math.max(0, level));
  const filled = Math.round(clamped * METER_CELLS);
  // A hot signal warns; it does not error. Clipping is recoverable.
  const tone = clamped > 0.92 ? "text-warn" : "text-phosphor";

  return (
    <div className="flex items-center gap-3">
      <span className="w-14 shrink-0">
        <SystemLabel>{label}</SystemLabel>
      </span>
      <span aria-hidden className={`font-mono text-xs leading-none ${tone}`}>
        {"█".repeat(filled)}
        <span className="text-ink-faint/40">{"░".repeat(METER_CELLS - filled)}</span>
      </span>
      <span className="font-mono text-2xs tabular-nums text-ink-faint">
        {db === undefined ? "—" : `${db > 0 ? "+" : ""}${db.toFixed(0)} dB`}
      </span>
    </div>
  );
}

/* ------------------------------------------------------------------ *
 * BootLine — > checking audio input.............. OK
 *
 * Used by the first-run model download, which is a real progress UI wearing
 * the boot sequence's clothes. See docs/09-EASTER-EGGS.md §2.
 * ------------------------------------------------------------------ */

export type BootState = "pending" | "active" | "ok" | "failed";

const BOOT: Record<BootState, { mark: string; tone: string }> = {
  pending: { mark: "", tone: "text-ink-faint" },
  active: { mark: "····", tone: "text-ink-faint" },
  ok: { mark: "OK", tone: "text-phosphor" },
  failed: { mark: "FAIL", tone: "text-error" },
};

export function BootLine({ label, state }: { label: string; state: BootState }) {
  const { mark, tone } = BOOT[state];

  return (
    <div className="flex items-baseline gap-1 font-mono text-xs">
      <span aria-hidden className="text-ink-faint">
        &gt;
      </span>
      <span className="text-ink-muted">{label}</span>
      <span aria-hidden className="trace-leader" />
      <span className={tone}>{mark}</span>
    </div>
  );
}
