/**
 * TRACE — terminal grammar components.
 *
 * The approved primitive set from docs/09-EASTER-EGGS.md, and deliberately
 * nothing more. New retro decoration should be argued for and added here,
 * not improvised at the call site.
 *
 * Utility classes below (`text-ink`, `font-mono`, `text-2xs`, `tracking-system`…)
 * are generated by Tailwind v4 from the `@theme` block in design/tokens.css.
 */

import { type ReactNode, useEffect, useId, useState } from "react";

/* ------------------------------------------------------------------ *
 * SystemLabel — uppercase, tracked, monospace. The workhorse.
 *   NOTES     TRANSCRIPT     SIGNAL
 * ------------------------------------------------------------------ */

const LABEL_TONE = {
  faint: "text-ink-faint",
  muted: "text-ink-muted",
  phosphor: "text-phosphor",
} as const;

export function SystemLabel({
  children,
  tone = "faint",
}: {
  children: ReactNode;
  tone?: keyof typeof LABEL_TONE;
}) {
  return <span className={`trace-system-label ${LABEL_TONE[tone]}`}>{children}</span>;
}

/* ------------------------------------------------------------------ *
 * Prompt — the `> ` in front of system messages:  > no traces yet.
 *
 * A component rather than a literal so a family that is not a terminal can
 * drop it in one rule (`.trace-glyph`), instead of every message carrying a
 * glyph its look does not speak. Hidden from screen readers, which read it
 * as "greater than".
 * ------------------------------------------------------------------ */

export function Prompt() {
  return (
    <span aria-hidden className="trace-glyph">
      &gt;{" "}
    </span>
  );
}

/* ------------------------------------------------------------------ *
 * Section — the canonical framing:
 *   ┌ 01  SUMMARY ──────────────────────────────────
 *
 * `index` is optional; omit it for unnumbered sections rather than
 * inventing a second framing style.
 * ------------------------------------------------------------------ */

export function Section({
  title,
  index,
  actions,
  children,
}: {
  title: string;
  index?: number;
  actions?: ReactNode;
  children: ReactNode;
}) {
  return (
    <section className="trace-section">
      <SectionHead title={title} index={index} actions={actions} />
      {children}
    </section>
  );
}

/* ------------------------------------------------------------------ *
 * SectionHead — the framing itself, isolated.
 *
 * Every section heading in the product goes through here, which is what
 * makes the rule-vs-box switch a CSS change rather than an edit in six
 * files. The corner glyph belongs to the rule treatment and is hidden in
 * box mode, where the border draws its own corner.
 * ------------------------------------------------------------------ */

export function SectionHead({
  title,
  index,
  actions,
  level = 2,
  toggle,
}: {
  title: string;
  index?: number | undefined;
  actions?: ReactNode;
  /**
   * Heading level this section sits at. Two by default, under the screen's
   * own `h1`.
   *
   * A note is a document, and its sections — Summary, Decisions, Transcript —
   * were styled spans inside a `<header>`. They looked like headings and were
   * not ones, so a screen reader got no outline of a note at all and no way
   * to jump between its parts. The visual treatment is unchanged; this only
   * makes the structure true.
   */
  level?: 2 | 3;
  /** Makes the title the control that opens and closes the section. */
  toggle?: { open: boolean; onToggle: () => void; controls: string } | undefined;
}) {
  const Heading = level === 3 ? "h3" : "h2";
  const label = <SystemLabel tone="muted">{title}</SystemLabel>;

  return (
    <header className="trace-section-head">
      <span aria-hidden className="trace-section-corner font-mono text-2xs text-ink-faint/50">
        ┌
      </span>
      {index !== undefined && (
        <SystemLabel tone="phosphor">{String(index).padStart(2, "0")}</SystemLabel>
      )}
      {/* The heading carries no styling of its own — SystemLabel still owns
          the look, so the theme switches keep working untouched. */}
      <Heading className="contents">
        {toggle ? (
          // The button sits inside the heading, not around it, so the outline
          // a screen reader walks is still made of headings.
          <button
            type="button"
            onClick={toggle.onToggle}
            aria-expanded={toggle.open}
            // Only while the body exists; closed, it is not in the DOM.
            aria-controls={toggle.open ? toggle.controls : undefined}
            className="flex items-center gap-1.5 rounded-xs trace-press hover:[&_.trace-system-label]:text-ink"
          >
            <span aria-hidden className="w-2.5 font-mono text-2xs text-ink-faint">
              {toggle.open ? "▾" : "▸"}
            </span>
            {label}
          </button>
        ) : (
          label
        )}
      </Heading>
      <span aria-hidden className="trace-rule" />
      {actions}
    </header>
  );
}

/* ------------------------------------------------------------------ *
 * Collapsible — a Section whose title opens and closes it.
 *
 * Still a `.trace-section`, so it frames as a rule or a box with the theme
 * like any other. Closed, the body is removed rather than hidden, which a
 * long transcript makes worth doing.
 * ------------------------------------------------------------------ */

export function Collapsible({
  title,
  defaultOpen = true,
  children,
}: {
  title: string;
  defaultOpen?: boolean;
  children: ReactNode;
}) {
  const [open, setOpen] = useState(defaultOpen);
  const id = useId();

  return (
    <section className="trace-section" data-open={open}>
      <SectionHead
        title={title}
        toggle={{ open, onToggle: () => setOpen((o) => !o), controls: id }}
      />
      {open && <div id={id}>{children}</div>}
    </section>
  );
}

/* ------------------------------------------------------------------ *
 * StatusDot — ● CAPTURING / ● TRANSCRIBING / ○ IDLE
 *
 * The single most important piece of state in the product. It pulses only
 * while genuinely capturing, so the motion always means the same thing.
 * ------------------------------------------------------------------ */

export type CaptureState = "idle" | "capturing" | "transcribing" | "processing" | "error";

const STATUS: Record<CaptureState, { label: string; dot: string; text: string; live: boolean }> = {
  idle: { label: "IDLE", dot: "bg-ink-faint", text: "text-ink-faint", live: false },
  capturing: { label: "CAPTURING", dot: "bg-phosphor", text: "text-phosphor", live: true },
  transcribing: { label: "TRANSCRIBING", dot: "bg-phosphor", text: "text-phosphor", live: true },
  processing: { label: "PROCESSING", dot: "bg-warn", text: "text-warn", live: true },
  error: { label: "SIGNAL LOST", dot: "bg-error", text: "text-error", live: false },
};

export function StatusDot({ state }: { state: CaptureState }) {
  const { label, dot, text, live } = STATUS[state];

  return (
    // role=status so a screen reader announces capture starting and stopping.
    <span role="status" className="inline-flex items-center gap-2">
      <span aria-hidden className={`size-1.5 rounded-full ${dot} ${live ? "trace-pulse" : ""}`} />
      <span className={`font-mono text-2xs uppercase tracking-system ${text}`}>{label}</span>
    </span>
  );
}

/* ------------------------------------------------------------------ *
 * Elapsed — 00:41:32
 * ------------------------------------------------------------------ */

export function formatElapsed(ms: number): string {
  const total = Math.max(0, Math.floor(ms / 1000));
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  const pad = (n: number) => String(n).padStart(2, "0");
  return h > 0 ? `${pad(h)}:${pad(m)}:${pad(s)}` : `${pad(m)}:${pad(s)}`;
}

export function Elapsed({ ms }: { ms: number }) {
  return (
    // tabular-nums stops the timer jittering as digits change width.
    <time
      className="font-mono text-base tabular-nums text-ink"
      dateTime={`PT${Math.round(ms / 1000)}S`}
    >
      {formatElapsed(ms)}
    </time>
  );
}

/* ------------------------------------------------------------------ *
 * Meter — MIC  ████████████░░░░  -12 dB
 *
 * Functional feedback, not decoration: it is how the user knows the
 * microphone is actually working before they trust a meeting to it.
 * ------------------------------------------------------------------ */

const METER_CELLS = 16;

export function Meter({
  label,
  /** Normalised 0..1 level. */
  level,
  db,
}: {
  label: string;
  level: number;
  db?: number | undefined;
}) {
  const clamped = Math.min(1, Math.max(0, level));
  // A hot signal warns; it does not error. Clipping is recoverable.
  const hot = clamped > 0.92;

  return (
    <div className="flex items-center gap-3">
      <span className="w-14 shrink-0">
        <SystemLabel>{label}</SystemLabel>
      </span>
      {/*
        The bar is a CSS fill rather than repeated block characters, so a
        theme can make it solid, dithered or a hue ramp without the component
        knowing which. Quantised to whole cells regardless, because a meter
        that slides continuously reads as an animation rather than a reading.
      */}
      <span aria-hidden className="trace-gauge shrink-0 text-xs leading-none">
        <span
          data-hot={hot}
          className="trace-fill h-2.5 w-40"
          style={
            { "--fill": Math.round(clamped * METER_CELLS) / METER_CELLS } as React.CSSProperties
          }
        />
      </span>
      <span className="font-mono text-2xs tabular-nums text-ink-faint">
        {db === undefined ? "—" : `${db > 0 ? "+" : ""}${db.toFixed(0)} dB`}
      </span>
    </div>
  );
}

/* ------------------------------------------------------------------ *
 * BootLine — > checking audio input.............. OK
 *
 * Used by the first-run model download, which is a real progress UI wearing
 * the boot sequence's clothes. See docs/09-EASTER-EGGS.md §2.
 * ------------------------------------------------------------------ */

export type BootState = "pending" | "active" | "ok" | "failed";

const BOOT: Record<BootState, { mark: string; tone: string }> = {
  pending: { mark: "", tone: "text-ink-faint" },
  active: { mark: "····", tone: "text-ink-faint" },
  ok: { mark: "OK", tone: "text-phosphor" },
  failed: { mark: "FAIL", tone: "text-error" },
};

export function BootLine({ label, state }: { label: string; state: BootState }) {
  const { mark, tone } = BOOT[state];

  return (
    <div className="flex items-baseline gap-1 font-mono text-xs">
      <span aria-hidden className="text-ink-faint">
        &gt;
      </span>
      <span className="text-ink-muted">{label}</span>
      <span aria-hidden className="trace-leader" />
      <span className={tone}>{mark}</span>
    </div>
  );
}

/* ------------------------------------------------------------------ *
 * Spinner — ⠋ ⠙ ⠹ ⠸
 *
 * Braille cells, the same width in every frame, so the line beside it does
 * not jitter. Only ever shown for work that is genuinely happening: the
 * frames are a clock, but whether it is on screen is backend state.
 *
 * Under reduced motion it holds one full cell rather than stepping. A
 * travelling glyph is exactly the small repetitive movement that setting
 * exists to stop, and a still one still says "busy".
 * ------------------------------------------------------------------ */

const SPINNER_FRAMES = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"];
const SPINNER_MS = 90;

export function Spinner({ className = "" }: { className?: string }) {
  const [frame, setFrame] = useState(0);
  const still = prefersReducedMotion();

  useEffect(() => {
    if (still) return;
    const id = window.setInterval(
      () => setFrame((f) => (f + 1) % SPINNER_FRAMES.length),
      SPINNER_MS,
    );
    return () => window.clearInterval(id);
  }, [still]);

  return (
    <span aria-hidden className={`inline-block shrink-0 tabular-nums ${className}`}>
      {still ? "⣿" : SPINNER_FRAMES[frame]}
    </span>
  );
}

function prefersReducedMotion(): boolean {
  return (
    typeof window !== "undefined" &&
    typeof window.matchMedia === "function" &&
    window.matchMedia("(prefers-reduced-motion: reduce)").matches
  );
}

/* ------------------------------------------------------------------ *
 * Gauge — [ ██████░░░░ ] 2/5
 *
 * The same fill the meters use, so themes restyle it with them. Only for a
 * real fraction: parts of a meeting done, bytes downloaded. Work with no
 * honest percentage gets a Spinner and a clock instead.
 * ------------------------------------------------------------------ */

export function Gauge({
  value,
  label,
  className = "w-16",
}: {
  /** 0..1. */
  value: number;
  /** Read out instead of the bar. */
  label: string;
  className?: string;
}) {
  return (
    <span role="img" aria-label={label} className="trace-gauge shrink-0 text-2xs leading-none">
      <span
        className={`trace-fill h-1.5 ${className}`}
        style={{ "--fill": Math.min(1, Math.max(0, value)) } as React.CSSProperties}
      />
    </span>
  );
}
